package com.lutera.app.ui

import android.content.Intent
import android.os.Bundle
import android.widget.Button
import androidx.appcompat.app.AppCompatActivity
import androidx.recyclerview.widget.LinearLayoutManager
import androidx.recyclerview.widget.RecyclerView
import com.lutera.app.R
import com.lutera.app.adapter.GameAdapter
import com.lutera.app.model.Game
import com.lutera.app.service.BotFloatingService

class GameListActivity : AppCompatActivity() {

    private lateinit var gameAdapter: GameAdapter
    private val games = mutableListOf<Game>()

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_game_list)
        
        val gamesRecyclerView = findViewById<RecyclerView>(R.id.gamesRecyclerView)
        val addGameButton = findViewById<Button>(R.id.addGameButton)
        val logoutButton = findViewById<Button>(R.id.logoutButton)
        
        gameAdapter = GameAdapter(games) { game ->
            val intent = Intent(this, GameWebViewActivity::class.java)
            intent.putExtra("gameUrl", game.url)
            intent.putExtra("gameName", game.name)
            startActivity(intent)
        }
        
        gamesRecyclerView.layoutManager = LinearLayoutManager(this)
        gamesRecyclerView.adapter = gameAdapter
        
        addGameButton.setOnClickListener {
            startActivity(Intent(this, AddGameActivity::class.java))
        }
        
        logoutButton.setOnClickListener {
            val sharedPref = getSharedPreferences("Lutera", MODE_PRIVATE)
            with(sharedPref.edit()) {
                putBoolean("isLoggedIn", false)
                clear()
                apply()
            }
            startActivity(Intent(this, LoginActivity::class.java))
            finish()
        }
        
        loadGames()
        startBotService()
    }

    private fun loadGames() {
        games.clear()
        games.add(Game("Aviator", "https://www.eg333.io"))
        games.add(Game("FlyX", "https://www.eg333.io"))
        games.add(Game("Go Rush", "https://www.eg333.io"))
        games.add(Game("High Flyer", "https://www.eg333.io"))
        games.add(Game("JetX", "https://www.eg333.io"))
        games.add(Game("FlyX Cash Turbo", "https://www.eg333.io"))
        games.add(Game("Crash Cricket", "https://www.eg333.io"))
        games.add(Game("Red Baron RNG", "https://www.eg333.io"))
        games.add(Game("Skylight Wonders", "https://www.eg333.io"))
        games.add(Game("Aviabet", "https://www.eg333.io"))
        games.add(Game("Galaxy Burst", "https://www.eg333.io"))
        games.add(Game("Aviator Extra Bet", "https://www.eg333.io"))
        games.add(Game("Roulette", "https://www.eg333.io"))
        games.add(Game("First Person Lightning Roulette", "https://www.eg333.io"))
        games.add(Game("Fortune Roulette", "https://www.eg333.io"))
        games.add(Game("European Roulette", "https://www.eg333.io"))
        games.add(Game("First Person Roulette", "https://www.eg333.io"))
        games.add(Game("Mines", "https://www.eg333.io"))
        games.add(Game("Mines+", "https://www.eg333.io"))
        games.add(Game("Mines Gold", "https://www.eg333.io"))
        games.add(Game("TowerX", "https://www.eg333.io"))
        games.add(Game("Coin Toss", "https://www.eg333.io"))
        games.add(Game("Andar Bahar", "https://www.eg333.io"))
        games.add(Game("Aviator", "https://www.bk33.org"))
        games.add(Game("FlyX", "https://www.bk33.org"))
        games.add(Game("Go Rush", "https://www.bk33.org"))
        games.add(Game("High Flyer", "https://www.bk33.org"))
        games.add(Game("JetX", "https://www.bk33.org"))
        games.add(Game("FlyX Cash Turbo", "https://www.bk33.org"))
        games.add(Game("Crash Cricket", "https://www.bk33.org"))
        games.add(Game("Red Baron RNG","https://www.bk33.org"))
        games.add(Game("Skylight Wonders", "https://www.bk33.org"))
        games.add(Game("Aviabet", "https://www.bk33.org"))
        games.add(Game("Galaxy Burst", "https://www.bk33.org"))
        games.add(Game("Aviator Extra Bet", "https://www.bk33.org"))
        games.add(Game("Roulette", "https://www.bk33.org"))
        games.add(Game("First Person Lightning Roulette", "https://www.bk33.org"))
        games.add(Game("Fortune Roulette", "https://www.bk33.org"))
        games.add(Game("European Roulette", "https://www.bk33.org"))
        games.add(Game("First Person Roulette", "https://www.bk33.org"))
        games.add(Game("Mines", "https://www.bk33.org"))
        games.add(Game("Mines+", "https://www.bk33.org"))
        games.add(Game("Mines Gold", "https://www.bk33.org"))
        games.add(Game("TowerX", "https://www.bk33.org"))
        games.add(Game("Coin Toss", "https://www.bk33.org"))
        games.add(Game("Andar Bahar", "https://www.bk33.org"))
        games.add(Game("Aviator", "https://www.a777bd.com"))
        games.add(Game("FlyX", "https://www.a777bd.com"))
        games.add(Game("Go Rush", "https://www.a777bd.com"))
        games.add(Game("High Flyer", "https://www.a777bd.com"))
        games.add(Game("JetX", "https://www.a777bd.com"))
        games.add(Game("FlyX Cash Turbo", "https://www.a777bd.com"))
        games.add(Game("Crash Cricket", "https://www.a777bd.com"))
        games.add(Game("Red Baron RNG", "https://www.a777bd.com"))
        games.add(Game("Skylight Wonders", "https://www.a777bd.com"))
        games.add(Game("Aviabet", "https://www.a777bd.com"))
        games.add(Game("Galaxy Burst", "https://www.a777bd.com"))
        games.add(Game("Aviator Extra Bet", "https://www.a777bd.com"))
        games.add(Game("Roulette", "https://www.a777bd.com"))
        games.add(Game("First Person Lightning Roulette", "https://www.a777bd.com"))
        games.add(Game("Fortune Roulette", "https://www.a777bd.com"))
        games.add(Game("European Roulette", "https://www.a777bd.com"))
        games.add(Game("First Person Roulette", "https://www.a777bd.com"))
        games.add(Game("Mines", "https://www.a777bd.com"))
        games.add(Game("Mines+", "https://www.a777bd.com"))
        games.add(Game("Mines Gold", "https://www.a777bd.com"))
        games.add(Game("TowerX", "https://www.a777bd.com"))
        games.add(Game("Coin Toss", "https://www.a777bd.com"))
        games.add(Game("Andar Bahar", "https://www.a777bd.com"))
        games.add(Game("Aviator", "https://www.bd222login.com"))
        games.add(Game("FlyX", "https://www.bd222login.com"))
        games.add(Game("Go Rush", "https://www.bd222login.com"))
        games.add(Game("High Flyer", "https://www.bd222login.com"))
        games.add(Game("JetX", "https://www.bd222login.com"))
        games.add(Game("FlyX Cash Turbo", "https://www.bd222login.com"))
        games.add(Game("Crash Cricket", "https://www.bd222login.com"))
        games.add(Game("Red Baron RNG", "https://www.bd222login.com"))
        games.add(Game("Skylight Wonders", "https://www.bd222login.com"))
        games.add(Game("Aviabet", "https://www.bd222login.com"))
        games.add(Game("Galaxy Burst", "https://www.bd222login.com"))
        games.add(Game("Aviator Extra Bet", "https://www.bd222login.com"))
        games.add(Game("Roulette", "https://www.bd222login.com"))
        games.add(Game("First Person Lightning Roulette", "https://www.bd222login.com"))
        games.add(Game("Fortune Roulette", "https://www.bd222login.com"))
        games.add(Game("European Roulette", "https://www.bd222login.com"))
        games.add(Game("First Person Roulette", "https://www.bd222login.com"))
        games.add(Game("Mines", "https://www.bd222login.com"))
        games.add(Game("Mines+", "https://www.bd222login.com"))
        games.add(Game("Mines Gold", "https://www.bd222login.com"))
        games.add(Game("TowerX", "https://www.bd222login.com"))
        games.add(Game("Coin Toss", "https://www.bd222login.com"))
        games.add(Game("Andar Bahar", "https://www.bd222login.com"))
        games.add(Game("Aviator", "https://www.www-ck44.com"))
        games.add(Game("FlyX", "https://www.www-ck44.com"))
        games.add(Game("Go Rush", "https://www.www-ck44.com"))
        games.add(Game("High Flyer", "https://www.www-ck44.com"))
        games.add(Game("JetX", "https://www.www-ck44.com"))
        games.add(Game("FlyX Cash Turbo", "https://www.www-ck44.com"))
        games.add(Game("Crash Cricket", "https://www.www-ck44.com"))
        games.add(Game("Red Baron RNG", "https://www.www-ck44.com"))
        games.add(Game("Skylight Wonders", "https://www.www-ck44.com"))
        games.add(Game("Aviabet", "https://www.www-ck44.com"))
        games.add(Game("Galaxy Burst", "https://www.www-ck44.com"))
        games.add(Game("Aviator Extra Bet", "https://www.www-ck44.com"))
        games.add(Game("Roulette", "https://www.www-ck44.com"))
        games.add(Game("First Person Lightning Roulette", "https://www.www-ck44.com"))
        games.add(Game("Fortune Roulette", "https://www.www-ck44.com"))
        games.add(Game("European Roulette", "https://www.www-ck44.com"))
        games.add(Game("First Person Roulette", "https://www.www-ck44.com"))
        games.add(Game("Mines", "https://www.www-ck44.com"))
        games.add(Game("Mines+", "https://www.www-ck44.com"))
        games.add(Game("Mines Gold", "https://www.www-ck44.com"))
        games.add(Game("TowerX", "https://www.www-ck44.com"))
        games.add(Game("Coin Toss", "https://www.www-ck44.com"))
        games.add(Game("Andar Bahar", "https://www.www-ck44.com"))
        games.add(Game("Aviator", "https://www.cv666.net"))
        games.add(Game("FlyX", "https://www.cv666.net"))
        games.add(Game("Go Rush", "https://www.cv666.net"))
        games.add(Game("High Flyer", "https://www.cv666.net"))
        games.add(Game("JetX", "https://www.cv666.net"))
        games.add(Game("FlyX Cash Turbo", "https://www.cv666.net"))
        games.add(Game("Crash Cricket", "https://www.cv666.net"))
        games.add(Game("Red Baron RNG", "https://www.cv666.net"))
        games.add(Game("Skylight Wonders", "https://www.cv666.net"))
        games.add(Game("Aviabet", "https://www.cv666.net"))
        games.add(Game("Galaxy Burst", "https://www.cv666.net"))
        games.add(Game("Aviator Extra Bet", "https://www.cv666.net"))
        games.add(Game("Roulette", "https://www.cv666.net"))
        games.add(Game("First Person Lightning Roulette", "https://www.cv666.net"))
        games.add(Game("Fortune Roulette", "https://www.cv666.net"))
        games.add(Game("European Roulette", "https://www.cv666.net"))
        games.add(Game("First Person Roulette", "https://www.cv666.net"))
        games.add(Game("Mines", "https://www.cv666.net"))
        games.add(Game("Mines+", "https://www.cv666.net"))
        games.add(Game("Mines Gold", "https://www.cv666.net"))
        games.add(Game("TowerX", "https://www.cv666.net"))
        games.add(Game("Coin Toss", "https://www.cv666.net"))
        games.add(Game("Andar Bahar", "https://www.cv666.net"))
        games.add(Game("Aviator", "https://www.tk999vip.com"))
        games.add(Game("FlyX", "https://www.tk999vip.com"))
        games.add(Game("Go Rush", "https://www.tk999vip.com"))
        games.add(Game("High Flyer", "https://www.tk999vip.com"))
        games.add(Game("JetX", "https://www.tk999vip.com"))
        games.add(Game("FlyX Cash Turbo", "https://www.tk999vip.com"))
        games.add(Game("Crash Cricket", "https://www.tk999vip.com"))
        games.add(Game("Red Baron RNG", "https://www.tk999vip.com"))
        games.add(Game("Skylight Wonders", "https://www.tk999vip.com"))
        games.add(Game("Aviabet", "https://www.tk999vip.com"))
        games.add(Game("Galaxy Burst", "https://www.tk999vip.com"))
        games.add(Game("Aviator Extra Bet", "https://www.tk999vip.com"))
        games.add(Game("Roulette", "https://www.tk999vip.com"))
        games.add(Game("First Person Lightning Roulette", "https://www.tk999vip.com"))
        games.add(Game("Fortune Roulette", "https://www.tk999vip.com"))
        games.add(Game("European Roulette", "https://www.tk999vip.com"))
        games.add(Game("First Person Roulette", "https://www.tk999vip.com"))
        games.add(Game("Mines", "https://www.tk999vip.com"))
        games.add(Game("Mines+", "https://www.tk999vip.com"))
        games.add(Game("Mines Gold", "https://www.tk999vip.com"))
        games.add(Game("TowerX", "https://www.tk999vip.com"))
        games.add(Game("Coin Toss", "https://www.tk999vip.com"))
        games.add(Game("Andar Bahar", "https://www.tk999vip.com"))
        games.add(Game("Aviator", "https://www.3333bk.com"))
        games.add(Game("FlyX", "https://www.3333bk.com"))
        games.add(Game("Go Rush", "https://www.3333bk.com"))
        games.add(Game("High Flyer", "https://www.3333bk.com"))
        games.add(Game("JetX", "https://www.3333bk.com"))
        games.add(Game("FlyX Cash Turbo", "https://www.3333bk.com"))
        games.add(Game("Crash Cricket", "https://www.3333bk.com"))
        games.add(Game("Red Baron RNG", "https://www.3333bk.com"))
        games.add(Game("Skylight Wonders", "https://www.3333bk.com"))
        games.add(Game("Aviabet", "https://www.3333bk.com"))
        games.add(Game("Galaxy Burst", "https://www.3333bk.com"))
        games.add(Game("Aviator Extra Bet", "https://www.3333bk.com"))
        games.add(Game("Roulette", "https://www.3333bk.com"))
        games.add(Game("First Person Lightning Roulette", "https://www.3333bk.com"))
        games.add(Game("Fortune Roulette", "https://www.3333bk.com"))
        games.add(Game("European Roulette", "https://www.3333bk.com"))
        games.add(Game("First Person Roulette", "https://www.3333bk.com"))
        games.add(Game("Mines", "https://www.3333bk.com"))
        games.add(Game("Mines+", "https://www.3333bk.com"))
        games.add(Game("Mines Gold", "https://www.3333bk.com"))
        games.add(Game("TowerX", "https://www.3333bk.com"))
        games.add(Game("Coin Toss", "https://www.3333bk.com"))
        games.add(Game("Andar Bahar", "https://www.3333bk.com"))
        games.add(Game("Aviator", "https://3111bet.net"))
        games.add(Game("FlyX", "https://3111bet.net"))
        games.add(Game("Go Rush", "https://3111bet.net"))
        games.add(Game("High Flyer", "https://3111bet.net"))
        games.add(Game("JetX", "https://3111bet.net"))
        games.add(Game("FlyX Cash Turbo", "https://3111bet.net"))
        games.add(Game("Crash Cricket", "https://3111bet.net"))
        games.add(Game("Red Baron RNG", "https://3111bet.net"))
        games.add(Game("Skylight Wonders", "https://3111bet.net"))
        games.add(Game("Aviabet", "https://3111bet.net"))
        games.add(Game("Galaxy Burst", "https://3111bet.net"))
        games.add(Game("Aviator Extra Bet", "https://3111bet.net"))
        games.add(Game("Roulette", "https://3111bet.net"))
        games.add(Game("First Person Lightning Roulette", "https://3111bet.net"))
        games.add(Game("Fortune Roulette", "https://3111bet.net"))
        games.add(Game("European Roulette", "https://3111bet.net"))
        games.add(Game("First Person Roulette", "https://3111bet.net"))
        games.add(Game("Mines", "https://3111bet.net"))
        games.add(Game("Mines+", "https://3111bet.net"))
        games.add(Game("Mines Gold", "https://3111bet.net"))
        games.add(Game("TowerX", "https://3111bet.net"))
        games.add(Game("Coin Toss", "https://3111bet.net"))
        games.add(Game("Andar Bahar", "https://3111bet.net"))
        games.add(Game("Aviator", "https://www.499bet.bingo"))
        games.add(Game("FlyX", "https://www.499bet.bingo"))
        games.add(Game("Go Rush", "https://www.499bet.bingo"))
        games.add(Game("High Flyer", "https://www.499bet.bingo"))
        games.add(Game("JetX", "https://www.499bet.bingo"))
        games.add(Game("FlyX Cash Turbo", "https://www.499bet.bingo"))
        games.add(Game("Crash Cricket", "https://www.499bet.bingo"))
        games.add(Game("Red Baron RNG", "https://www.499bet.bingo"))
        games.add(Game("Skylight Wonders", "https://www.499bet.bingo"))
        games.add(Game("Aviabet", "https://www.499bet.bingo"))
        games.add(Game("Galaxy Burst", "https://www.499bet.bingo"))
        games.add(Game("Aviator Extra Bet", "https://www.499bet.bingo"))
        games.add(Game("Roulette", "https://www.499bet.bingo"))
        games.add(Game("First Person Lightning Roulette", "https://www.499bet.bingo"))
        games.add(Game("Fortune Roulette", "https://www.499bet.bingo"))
        games.add(Game("European Roulette", "https://www.499bet.bingo"))
        games.add(Game("First Person Roulette", "https://www.499bet.bingo"))
        games.add(Game("Mines", "https://www.499bet.bingo"))
        games.add(Game("Mines+", "https://www.499bet.bingo"))
        games.add(Game("Mines Gold", "https://www.499bet.bingo"))
        games.add(Game("TowerX", "https://www.499bet.bingo"))
        games.add(Game("Coin Toss", "https://www.499bet.bingo"))
        games.add(Game("Andar Bahar", "https://www.499bet.bingo"))
        games.add(Game("Aviator", "https://www.299betvip.com"))
        games.add(Game("FlyX", "https://www.299betvip.com"))
        games.add(Game("Go Rush", "https://www.299betvip.com"))
        games.add(Game("High Flyer", "https://www.299betvip.com"))
        games.add(Game("JetX", "https://www.299betvip.com"))
        games.add(Game("FlyX Cash Turbo", "https://www.299betvip.com"))
        games.add(Game("Crash Cricket", "https://www.299betvip.com"))
        games.add(Game("Red Baron RNG", "https://www.299betvip.com"))
        games.add(Game("Skylight Wonders", "https://www.299betvip.com"))
        games.add(Game("Aviabet", "https://www.299betvip.com"))
        games.add(Game("Galaxy Burst", "https://www.299betvip.com"))
        games.add(Game("Aviator Extra Bet", "https://www.299betvip.com"))
        games.add(Game("Roulette", "https://www.299betvip.com"))
        games.add(Game("First Person Lightning Roulette", "https://www.299betvip.com"))
        games.add(Game("Fortune Roulette", "https://www.299betvip.com"))
        games.add(Game("European Roulette", "https://www.299betvip.com"))
        games.add(Game("First Person Roulette", "https://www.299betvip.com"))
        games.add(Game("Mines", "https://www.299betvip.com"))
        games.add(Game("Mines+", "https://www.299betvip.com"))
        games.add(Game("Mines Gold", "https://www.299betvip.com"))
        games.add(Game("TowerX", "https://www.299betvip.com"))
        games.add(Game("Coin Toss", "https://www.299betvip.com"))
        games.add(Game("Andar Bahar", "https://www.299betvip.com"))
        gameAdapter.notifyDataSetChanged()
    }

    private fun startBotService() {
        val intent = Intent(this, BotFloatingService::class.java)
        startService(intent)
    }
}
